### ISSUE TITLE
Old variables persist, causing misleading results

### ISSUE THREAD

**Issue by jonahx** [martin-saurer/jkernel#10]
This is best demonstrated with a simple example:

### 1. create some erroneous definition
![step1](https://user-images.githubusercontent.com/699684/32147801-63c8dee0-bcc3-11e7-8900-ee51b586c72d.png)

The error is correct, since the definition of `f` is a syntax error.

### 2. now create a correct definition and "run cell" again

![step2](https://user-images.githubusercontent.com/699684/32147819-933ad020-bcc3-11e7-87db-d2d5a1add45d.png)
Still working as expected, since we've re-bound `f` to a valid definition.

### 3. now delete the correct definition and "run cell" again

![step3](https://user-images.githubusercontent.com/699684/32147829-b1a63dec-bcc3-11e7-9d47-503be1383eb5.png)

The result here *should be* the same as in step 1, but the correct definition of `f` is still hanging around...

**Comment by martin-saurer** [comment]
@jonahx 
J sentences in a notebook cell are feed to the J interpreter line-by-line. So the cell contents:
```
f=. & @ +
2 f 3
```
result in a value error because f has not evaluated to a definition. At the time when "2 f 3"
is executed, f does not exist.
Try only the sentence "f=. & @ +" in a cell. This results in a "syntax error", not in a "value error".
Yes, this behaviour can be misleading because only the error message of the last line is
displayed. I will investigate in that as soon as my time permits.

```
 f=. & @ +         <-- syntax error, but not displayed
 f=. +             <-- correct definition *1
 2 f 3             <-- correct evaluation

 f=. & @ +         <-- syntax error, but not displayed
 2 f 3             <-- correct evaluation because f from *1 is still defined
```

So the good news are that old definitions/variables do NOT persist.

**Comment by jonahx** [comment]
@martin-saurer 

Thanks for looking into it.

> Yes, this behaviour can be misleading because only the error message of the last line is
displayed. I will investigate in that as soon as my time permits.

Fwiw, I think either of these 2 options would avoid any confusion:
1. Display only the *first* error
2. Display all the errors

> So the good news are that old definitions/variables do NOT persist.

What about the behavior I'm seeing in item 3 from my OP?

**Comment by martin-saurer** [comment]
@jonahx 
The behavior of item 3 in your OP is what I tried to describe. The last “good” definition of f stays in effect until a new “good” definition is made. A “bad” definition of f (syntax error) does not overwrite or clear the last “good” definition of f.

**Comment by jonahx** [comment]
@martin-saurer 

> The behavior of item 3 in your OP is what I tried to describe. The last “good” definition of f stays in effect until a new “good” definition is made. A “bad” definition of f (syntax error) does not overwrite or clear the last “good” definition of f.

I think less confusing behavior would be for a "run cell" to wipe out the previous memory and behave as if the cell you see in front of you, right now, was all that ever existed.  Essentially, we want the code itself to be referentially transparent.   This is how it works for python notebooks, eg.

**Comment by martin-saurer** [comment]
Python also keeps variables from previous cells. Wipe out the memory for all previous cells, when running a new cell, is a bad idea.
