### ISSUE TITLE
Kernel does not exist

### ISSUE THREAD

**Issue by jonahx** [martin-saurer/jkernel#11]
I've followed the installation instructions inside a docker container, and the notebook comes up with the J kernel available in the dropdown on my host machine.  The python3 kernel works fine, but I get the following error when starting the J kernel:

```
[I 07:20:20.369 NotebookApp] Creating new notebook in 
[I 07:20:21.121 NotebookApp] Kernel started: 9af86efc-9000-4b35-abfd-9d5837604792
[I 07:20:24.121 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 07:20:27.156 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 07:20:30.186 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 07:20:33.204 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
[W 07:20:36.187 NotebookApp] KernelRestarter: restart failed
[W 07:20:36.188 NotebookApp] Kernel 9af86efc-9000-4b35-abfd-9d5837604792 died, removing from map.
[W 07:21:21.114 NotebookApp] Timeout waiting for kernel_info reply from 9af86efc-9000-4b35-abfd-9d5837604792
[E 07:21:21.116 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 9af86efc-9000-4b35-abfd-9d5837604792)
```

I'm not sure how to debug from here.  Any ideas what could be going wrong?

If you want to try it out I pushed the image here: https://hub.docker.com/r/jonahx/jupyter-j

Thanks.

EDIT: forget to mention, cmd to start the docker container on your host machine:

```
docker run -it --rm -p 8888:8888 docker.io/jonahx/jupyter-j
```

**Comment by martin-saurer** [comment]
I have very little experience with docker. Just to make sure: Normal jkernel installation (without docker) is still working for you?

**Comment by jonahx** [comment]
I haven't tried on linux (the docker image is a linux one) but have got this working on a mac before.

Fwiw, installing in a docker container should be no different than installing on linux bare metal.  So that's a red herring in all likelihood.  I thought of posting the issue without mentioning docker and just asking what could be causing that error, but figured I'd post the docker container just in case you wanted to try it yourself.  It makes it trivial to reproduce exactly what I'm seeing -- just required a docker install and a big download for the image.

Most likely cause is probably operator error (ie, me) but I followed the instructions so I'm not sure what I might have done wrong....

**Comment by jonahx** [comment]
One more thought on this.  I installed J 807.  I realized the docs state J 804.  Does it only work with the older version of J?

**Comment by martin-saurer** [comment]
Please take: https://github.com/martin-saurer/jkernel-docker as a source for your own Docker Image.
