### ISSUE TITLE
Issue installing on OSX with a locally installed Anaconda3

### ISSUE THREAD

**Issue by pcorey** [martin-saurer/jkernel#12]
Hi,

Following the steps on Jupyter's installation page, I downloaded Anaconda3 (Python 3 version) and installed it on my OSX (10.14) machine. It seems Anaconda3 only supports installation in the current user's home folder, and was installed under `$HOME/anaconda3`. I added `$HOME/anaconda3/bin` to my path and verified that Jupyter was installed successfully:

```
➜  ~ jupyter --version
4.4.0
```

Next, I cloned your repo and ran the installation command, which failed with the following errors:

```
➜  jkernel git:(master) python setup.py install

Check pre-requisites ...
Anaconda/Miniconda root directory ... : /Library MISSING or NOT writeable.
Site Packages directory ............. : /Library/Python/2.7/site-packages MISSING or NOT writeable.
Jupyter Notebook syntax directory ... : /Library/Python/2.7/site-packages/notebook/static/components/codemirror/mode MISSING or NOT writeable.
Jupyter Kernels directory ........... : /Library/share/jupyter/kernels MISSING or NOT writeable.
ERROR: One or more destination directories are not accessible !!!
```

What am I missing? Is the Python 2 version of Anaconda3 required?

**Comment by martin-saurer** [comment]
Hi,
To me, it looks like you run the python pre-installed on MacOS, not the one from Anaconda. Please add $HOME/anaconda3/bin as the first element of your PATH env variable, not the last element.
The Python3 version of Anaconda is required.

**Comment by pcorey** [comment]
@martin-saurer That was the problem. Everything's working now. That's for the help, and for all of your work in putting this together!
