### ISSUE TITLE
64-bit change

### ISSUE THREAD

**Issue by tingtron** [martin-saurer/jkernel#14]
A quick change is required to support 64-bit systems.

- in `jkernel/jinter.py` (which used to be called `qjide.py`)
In `def JWd()`, instead of 
`sptr = pointer(c_long(pa+8*sizeof(c_long)))`
use
`sptr = pointer(c_void_p(pa+8*sizeof(c_void_p)))`

This is due to how `struct A` is defined, see `jfex.h`.

It was tested on Windows 10 64-bit with Python 3.6 64-bit and J901 64-bit.

Hopefully, it could be incorporated in the repository.

**Comment by martin-saurer** [comment]
Thanks!
Fixed in latest upload.
