### ISSUE TITLE
J902 does not NULL terminate strings in C interface

### ISSUE THREAD

**Issue by tingtron** [martin-saurer/jkernel#16]
One issue is at #235 in `jinter.py`
 - either append NULL
```
string_encode3('tmpstr_jinter_ =: ({.a.),~jpath \'~user\''))
```
 - or somehow dereference `JShap` and pass it as second parameter (size) to `string_at`, which I couldn't figure out. 

### Reproduce / Test

```
load'plot'
plot ? 10$0
```
Error because `adCata` is extraneous part from non-null terminated string.
```
JKernel: Internal Error.
[Errno 2] No such file or directory: 'c:\\tools\\j902-useradCata\\temp\\plot.html'
```

### Background

- https://code.jsoftware.com/wiki/Guides/DLLs/Calling_DLLs#J807_Incompatibilities

Current J maintainers don't care about breaking existing C interfaces.
- https://github.com/jsoftware/jsource/issues/17

**Comment by martin-saurer** [comment]
Fixed in latest release.
Using shape to get string size.
