### ISSUE TITLE
Error when starting kernel

### ISSUE THREAD

**Issue by Fluffums** [martin-saurer/jkernel#2]
I get the following error when attempting to start the jkernel:

```
C:\Users\danew\Anaconda3\python.exe: Error while finding spec for 'jkernel.jkernel' (<class 'AttributeError'>: module 'jkernel' has no attribute '__path__')
```

- Windows 10 Pro
- 64-bit J v8
- Jupyter otherwise works
- J worked with the @adrian17 jkernel

`C:\Users\danew\Anaconda3\Lib\site-packages\jkernel\qjide.cfg` contains the following line:
`JInsFol = 'C:\\Users\\danew\\Google Drive\\Code\\j64-804'`

**Comment by martin-saurer** [comment]
@Fluffums Unfortunately I cannot reproduce this issue at this time, neither on Windows, Mac, or Linux. There are a lot of differences between @adrian17's jkernel and my version. Have you tried the following command: python -m jkernel.jkernel
If this gives you the same error message, there must be something with the anaconda installation.
Do you have both jkernels installed @adrian17 and my version?
May be they disrupt each other (or just mine ;-)

**Comment by Pascal-J** [comment]
a related question, and possible resolution, could this be renamed qjkernel?  Can we do this manually?

**Comment by martin-saurer** [comment]
@Fluffums @Pascal-J 
Finally I can reproduce this issue.
To me it looks it has something to do with the python search path (sys.path).

If you cd to: ...\Anaconda3\Lib\site-packages\jkernel
or: ...\Anaconda3\Lib\site-packages\
and run: python -m jkernel.jkernel
you will get the error: Error while finding spec for 'jkernel.jkernel' (<class 'AttributeError'>: module 'jkernel' has no attribute '__path__')

Try the same from your home directory: C:\Users\Martin (for example)
It should work now.

Starting: jupyter notebook from C:\ will also not do. You will get a: 404 : Not Found
in your browser (not jkernel related). It seems that the startup directory has some
(strange) effects, when starting jupyter notebook.

@Pascal-J 
Sure, you may rename the jkernel stuff to qjkernel (or what ever you wish ;-) as long as
you rename all the related stuff consistently.

**Comment by Fluffums** [comment]
Naming suggestion: how about "Jlang"?

Just running `jupyter notebook` from `C:\Users\Fluffums` still produced the error. I'll try going through fresh install steps on a clean Windows machine to see if I'm consistent.

I also just installed this on a fresh Linux machine and the kernel is dying for another reason...

**Comment by martin-saurer** [comment]
@Fluffums 
That's weird!
I run this stuff on Mac, Windows, Linux, and everything works right out of the box.
For me, it's a bit like fishing in troubled waters ;-)

My OS-Environment:
Windows: Windows 10 32/64-bit English
MacOSX: 10.11.4
Linux:       Ubuntu 14.04 64-bit

Latest Version of Anaconda3, with all the updates, but no additional packages from outside
the Anaconda distribution.

I'm thinking about renaming jkernel to Jlang ...

**Comment by reckbo** [comment]
FYI Martin's suggestion of starting the notebook from my home folder resolved this error for me (I'm on a Mac).

**Comment by Fluffums** [comment]
@martin-saurer - Wow. I finally got around to trying this again, and I got it working. I ran into a similar bug as before, but figured out it was due to a typo in the J install path in qjide.cfg. If I run into new issues using your JLang kernel in Jupyter, I'll open a new issue. Thank you for doing this!
