### ISSUE TITLE
Multi-line statements currently not supported

### ISSUE THREAD

**Issue by martin-saurer** [martin-saurer/jkernel#4]
Multi-line statements, like:

f1 =: 3 : 0
   y + 10
)

are currently not supported by jkernel.

qjide supports such statements because of it's asynchronous I/O structure.
Let's see how to do this in jupiter notebook.

**Comment by reckbo** [comment]
I was just about to post this issue :)

**Comment by martin-saurer** [comment]
@reckbo Multi-line statements are now possible. Have fun!

**Comment by reckbo** [comment]
Great, thanks!!
