### ISSUE TITLE
Pretty boxes

### ISSUE THREAD

**Issue by Fluffums** [martin-saurer/jkernel#6]
Can we get pretty boxes? Or are we stuck with`|-+`?

**Comment by martin-saurer** [comment]
@Fluffums 
For now, please add the line

   9!:7 (0{Boxes_j_)

to the file

   .../Anaconda/Lib/site-packages/jkernel/qjide.ijs

I will provide an official fix later.

**Comment by martin-saurer** [comment]
Latest version (as of 17.08.2016) contains this patch.
