### ISSUE TITLE
Run example notebooks so that GitHub shows results

### ISSUE THREAD

**Issue by DaneWeber** [martin-saurer/jkernel#8]
@martin-saurer - do you think you could run your example notebooks and commit those to the repo? I would expect doing so to make the GitHub views far more illustrative:
https://github.com/martin-saurer/jkernel/blob/master/examples/Compare_Bitmap_Images.ipynb

I was about to link directly to one of your example notebooks in GitHub, but they don't show what Jupyter can do.

**Comment by martin-saurer** [comment]
@DaneWeber - Yes, it looks that GitHub's notebook viewer is working for J notebooks now. Not for all features (interactive HTML), but for most. So I updated the example notebooks showing the results.

**Comment by DaneWeber** [comment]
Thanks!
