### ISSUE TITLE
does the J kernel require anaconda?

### ISSUE THREAD

**Issue by jonahx** [martin-saurer/jkernel#9]
I had it working when I was using anaconda-installed jupyter.

I recently switched to jupyter intalled via pip, and while the other kernels still work the J kernel hangs, dies, and keeps restarting.

Any way I could fix it?  I love using J in jupyter.

Thanks,
Jonah

**Comment by martin-saurer** [comment]
@jonahx 
Do you start jupyter from a terminal?
Can you please provide the terminal output of the jupyter session when you try to load the jkernel?

Thanks in advance,
Martin

**Comment by jonahx** [comment]
Thanks, your comment allowed me to fix it.

I just needed follow the same directions on the homepage but substituting the homebrew python path for the Anaconda one.  Got it working now.

Only part that still doesn't work is the syntax highlighting, but that didn't work on my Anaconda version either.  Any ideas what might be wrong there?
